[package]
name = "exposed"
version = "0.1.0"
edition = "2024"
readme = "README.md"
description = "Application that makes UK parliament data easy to search"
license.workspace = true 
categories.workspace = true 
keywords.workspace = true 
repository.workspace = true 


[lib]
path = "src/lib/lib.rs"

[lints]
workspace = true

[[bin]]
name = "exposed"
path = "src/bin/main.rs"


[dependencies]
bytes = "1.12.1"
libc = "0.2.189"
sha2 = "0.10.9"
tempfile = "3.27.0"
bigdecimal = "0.4.10"
anyhow = "1.0.104"
axum = "0.8.9"
chrono = { version = "0.4.45", features = ["serde"] }
time = "0.3.47"
clap = { version = "4.6.7", features = ["derive"] }
dotenvy = "0.15.7"
duckdb = { version = "=1.4.4", features = ["bundled"] }
rust-yaml = { version = "1.1.0", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["arbitrary_precision"] }
sqlx = { version = "0.9.0", features = ["postgres", "runtime-tokio","uuid", "time", "bigdecimal"] }
strum = { version = "0.28.0", features = ["derive", "strum_macros"] }
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["rt-multi-thread"] }
reqwest = "0.13.5"
arrow = { version = "60.0.0", features = ["async"] }
parquet = { version = "60.0.0", features = ["arrow", "async"] }
uuid = { version = "1.26.1", features = ["std", "v7", "serde"] }
futures = "0.3.34"
unicode-normalization = "0.1.25"

[dev-dependencies]
sqlx = { version = "0.9.0", features = ["postgres", "runtime-tokio", "migrate", "macros"] }
