[workspace]
members = ["exposed"]
resolver = "3"

[workspace.package]
license = "MIT OR Apache-2.0"
repository = "https://github.com/johnnylarner/exposed"
keywords = ["politics", "uk parliament"]
categories = ["application"]
rust-version = "1.94.0"

[workspace.lints.clippy]
cargo = { level = "deny", priority = -1 }
multiple_crate_versions = "allow"
