//! Operator HTTP adapter. Source commands are generated by the Rust Parliament adapter.
use axum::{
    Json, Router,
    extract::{DefaultBodyLimit, Path, State},
    http::{HeaderMap, StatusCode},
    routing::{get, post},
};
use chrono::NaiveDate;
use serde::Deserialize;
use serde_json::{Value, json};
use std::{
    collections::HashMap,
    sync::Arc,
    time::{Duration, Instant},
};
use tokio::{
    sync::{Mutex, mpsc, oneshot},
    task::JoinHandle,
};
use uuid::Uuid;

use super::{
    adapters::{
        parliament::{Parliament, Request, Response, Transport},
        postgres::PostgresStore,
    },
    config::ImportConfig,
    core::{
        ImportError, Result,
        coordinator::{ImportKind, run_import},
        ports::ImportStore,
    },
    runtime::SystemClock,
};

enum Event {
    Fetch(Request, oneshot::Sender<Response>),
    Finished(Value),
}
struct RemoteTransport(mpsc::Sender<Event>);
impl Transport for RemoteTransport {
    async fn fetch(&self, request: Request) -> Result<Response> {
        let (tx, rx) = oneshot::channel();
        self.0
            .send(Event::Fetch(request, tx))
            .await
            .map_err(|e| ImportError::source_failure("Operator disconnected", e))?;
        tokio::time::timeout(Duration::from_secs(300), rx)
            .await
            .map_err(|e| ImportError::source_failure("Operator source session expired", e))?
            .map_err(|e| ImportError::source_failure("Operator disconnected", e))
    }
}
struct Session {
    task: JoinHandle<()>,
    exchange: Mutex<Exchange>,
}
struct RegisteredSession {
    session: Arc<Session>,
    touched: Instant,
}
impl RegisteredSession {
    fn retain_unexpired(&self) -> bool {
        if self.touched.elapsed() >= Duration::from_secs(900) {
            self.session.task.abort();
            return false;
        }
        true
    }
}
struct Exchange {
    events: mpsc::Receiver<Event>,
    pending: Option<oneshot::Sender<Response>>,
    sequence: u64,
    last_submission: Option<Value>,
    message: Option<Value>,
}
impl Drop for Session {
    fn drop(&mut self) {
        self.task.abort();
    }
}
impl Exchange {
    async fn message(&mut self) -> Value {
        if let Some(message) = &self.message {
            return message.clone();
        }
        let message = match self.events.recv().await {
            Some(Event::Fetch(request, reply)) => {
                self.pending = Some(reply);
                json!({"sequence":self.sequence,"request":request})
            }
            Some(Event::Finished(result)) => result,
            None => json!({"error":"Import task stopped; retry the import"}),
        };
        self.message = Some(message.clone());
        message
    }
}

#[derive(Clone)]
pub(crate) struct AdminState {
    store: PostgresStore,
    config: Arc<ImportConfig>,
    token: Option<String>,
    sessions: Arc<Mutex<HashMap<Uuid, RegisteredSession>>>,
}
impl AdminState {
    pub fn new(store: PostgresStore, config: Arc<ImportConfig>, token: Option<String>) -> Self {
        Self {
            store,
            config,
            token,
            sessions: Arc::new(Mutex::new(HashMap::new())),
        }
    }
    fn authorize(&self, headers: &HeaderMap) -> std::result::Result<(), (StatusCode, Json<Value>)> {
        if let Some(token) = &self.token {
            if headers.get("authorization").and_then(|h| h.to_str().ok())
                != Some(format!("Bearer {token}").as_str())
            {
                return Err((
                    StatusCode::UNAUTHORIZED,
                    Json(json!({"error":"Invalid operator token"})),
                ));
            }
        }
        Ok(())
    }
    pub async fn expire_sessions(&self) {
        self.sessions
            .lock()
            .await
            .retain(|_, session| session.retain_unexpired());
    }
}

type HttpResult = std::result::Result<Json<Value>, (StatusCode, Json<Value>)>;
fn bad(status: StatusCode, message: &str) -> (StatusCode, Json<Value>) {
    (status, Json(json!({"error":message})))
}

#[derive(Deserialize)]
struct Begin {
    kind: ImportKind,
    term_start: Option<NaiveDate>,
}

async fn begin(
    State(state): State<AdminState>,
    Path(id): Path<Uuid>,
    headers: HeaderMap,
    Json(body): Json<Begin>,
) -> HttpResult {
    state.authorize(&headers)?;
    let term = body.term_start.unwrap_or(state.config.term_start);
    if term != state.config.term_start {
        return Err(bad(
            StatusCode::UNPROCESSABLE_ENTITY,
            "Term differs from the Rust application configuration",
        ));
    }
    let mut sessions = state.sessions.lock().await;
    sessions.retain(|_, session| session.retain_unexpired());
    if let Some(session) = sessions.get_mut(&id) {
        session.touched = Instant::now();
        let session = Arc::clone(&session.session);
        drop(sessions);
        let message = session.exchange.lock().await.message().await;
        return Ok(Json(message));
    }
    if sessions.len() >= 32 {
        return Err(bad(
            StatusCode::TOO_MANY_REQUESTS,
            "Too many import sessions; retry later",
        ));
    }
    let (tx, events) = mpsc::channel(1);
    let store = state.store.clone();
    let interval = state.config.notification_interval_seconds;
    let task = tokio::spawn(async move {
        let source = Parliament(RemoteTransport(tx.clone()));
        let as_of = chrono::Utc::now()
            .with_timezone(&chrono_tz::Europe::London)
            .date_naive();
        let result = run_import(
            body.kind,
            term,
            as_of,
            &source,
            &store,
            &SystemClock,
            interval,
            false,
        )
        .await;
        let message = match result {
            Ok(result) => json!({"result":result}),
            Err(error) => {
                eprintln!("Operator import: {error:?}");
                json!({"error":error.to_string()})
            }
        };
        let _ = tx.send(Event::Finished(message)).await;
    });
    let session = Arc::new(Session {
        task,
        exchange: Mutex::new(Exchange {
            events,
            pending: None,
            sequence: 0,
            last_submission: None,
            message: None,
        }),
    });
    sessions.insert(
        id,
        RegisteredSession {
            session: Arc::clone(&session),
            touched: Instant::now(),
        },
    );
    drop(sessions);
    let message = session.exchange.lock().await.message().await;
    Ok(Json(message))
}

#[derive(Deserialize)]
struct Submission {
    sequence: u64,
    response: Response,
}
async fn evidence(
    State(state): State<AdminState>,
    Path(id): Path<Uuid>,
    headers: HeaderMap,
    Json(body): Json<Submission>,
) -> HttpResult {
    state.authorize(&headers)?;
    let mut sessions = state.sessions.lock().await;
    let session = sessions.get_mut(&id).ok_or_else(|| {
        bad(
            StatusCode::NOT_FOUND,
            "Import session expired; rerun safely",
        )
    })?;
    session.touched = Instant::now();
    let session = Arc::clone(&session.session);
    drop(sessions);
    let mut session = session.exchange.lock().await;
    let raw = json!(body.response);
    if body.sequence.checked_add(1) == Some(session.sequence)
        && session.last_submission.as_ref() == Some(&raw)
    {
        return Ok(Json(session.message().await));
    }
    if body.sequence != session.sequence {
        return Err(bad(StatusCode::CONFLICT, "Unexpected evidence sequence"));
    }
    let reply = session
        .pending
        .take()
        .ok_or_else(|| bad(StatusCode::CONFLICT, "No evidence requested"))?;
    reply
        .send(body.response)
        .map_err(|_| bad(StatusCode::GONE, "Import source session expired"))?;
    session.sequence += 1;
    session.last_submission = Some(raw);
    session.message = None;
    Ok(Json(session.message().await))
}

async fn cancel(
    State(state): State<AdminState>,
    Path(id): Path<Uuid>,
    headers: HeaderMap,
) -> HttpResult {
    state.authorize(&headers)?;
    if let Some(session) = state.sessions.lock().await.remove(&id) {
        // The exchange may be waiting on publication. Abort without taking that lock.
        session.session.task.abort();
    }
    Ok(Json(json!({"status":"cancelled"})))
}
async fn status(State(state): State<AdminState>, headers: HeaderMap) -> HttpResult {
    state.authorize(&headers)?;
    let refresh = state
        .store
        .refresh_state(state.config.term_start)
        .await
        .map_err(|error| {
            eprintln!("Import status: {error:?}");
            bad(
                StatusCode::INTERNAL_SERVER_ERROR,
                "Could not read refresh state",
            )
        })?;
    Ok(Json(json!(refresh)))
}

pub(crate) fn router(state: AdminState) -> Router {
    Router::new()
        .route("/imports/status", get(status))
        .route("/imports/{id}", post(begin).delete(cancel))
        .route("/imports/{id}/evidence", post(evidence))
        .layer(DefaultBodyLimit::max(32 * 1024 * 1024))
        .with_state(state)
}
